// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2p0MtGhhm-3yj3dNWyx_Qms9vpeKqz6o',
    appId: '1:764798571355:web:f2da35192cd3e9623dc07e',
    messagingSenderId: '764798571355',
    projectId: 'continuum-health-b54cb',
    authDomain: 'continuum-health-b54cb.firebaseapp.com',
    storageBucket: 'continuum-health-b54cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2p0MtGhhm-3yj3dNWyx_Qms9vpeKqz6o',
    appId: '1:764798571355:android:f2da35192cd3e9623dc07e',
    messagingSenderId: '764798571355',
    projectId: 'continuum-health-b54cb',
    storageBucket: 'continuum-health-b54cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWM-0GZR5gy9zHLmMrSUMt1xbLBpqTlNI',
    appId: '1:764798571355:ios:32a10763a7eeb1853dc07e',
    messagingSenderId: '764798571355',
    projectId: 'continuum-health-b54cb',
    storageBucket: 'continuum-health-b54cb.firebasestorage.app',
    iosBundleId: 'com.continuumhealth.continuumHealth',
  );
}
