import 'package:flutter/material.dart';
import 'package:lucide_icons/lucide_icons.dart';

import '../../../../core/theme/app_colors.dart';
import '../../../../data/models/twin_state_model.dart';
import '../../../../data/services/backend_service.dart';

/// Modal bottom sheet providing transparent, explainable 7-stage decision tracing
/// for any proactive recommendation generated by the TWIN State Engine.
///
/// The 7 Stages:
/// 1. OBSERVED  - Sensor Telemetry (Heart rate, steps, motion, SpO2, temp, humidity)
/// 2. CONTEXT   - Care & Recovery Context (Medications, appointments, care gaps, trajectory)
/// 3. WHY NOW   - Opportunity Engine Evaluation (Timing, quiet hours, cooldowns, budget)
/// 4. DECISION  - Deterministic Evaluation Rule & Rationale
/// 5. ACTION    - Proactive Suggestion & FollowUpPlan trigger
/// 6. OUTCOME   - Closed-loop post-intervention sensor observations
/// 7. LEARNING  - Autonomous behavioral pattern update & memory adaptation
class TwinDecisionTraceSheet extends StatefulWidget {
  final String patientId;
  final String recommendationId;
  final BackendService backendService;
  final TwinDecisionTraceModel? initialTrace;
  final TwinRecommendationModel? recommendation;

  const TwinDecisionTraceSheet({
    super.key,
    required this.patientId,
    required this.recommendationId,
    required this.backendService,
    this.initialTrace,
    this.recommendation,
  });

  static Future<void> show(
    BuildContext context, {
    required String patientId,
    required String recommendationId,
    required BackendService backendService,
    TwinDecisionTraceModel? initialTrace,
    TwinRecommendationModel? recommendation,
  }) {
    return showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => TwinDecisionTraceSheet(
        patientId: patientId,
        recommendationId: recommendationId,
        backendService: backendService,
        initialTrace: initialTrace,
        recommendation: recommendation,
      ),
    );
  }

  @override
  State<TwinDecisionTraceSheet> createState() => _TwinDecisionTraceSheetState();
}

class _TwinDecisionTraceSheetState extends State<TwinDecisionTraceSheet> {
  TwinDecisionTraceModel? _trace;
  bool _isLoading = false;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _trace = widget.initialTrace;
    if (_trace == null) {
      _fetchTrace();
    }
  }

  Future<void> _fetchTrace() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      final trace = await widget.backendService.getTwinDecisionTrace(
        widget.patientId,
        widget.recommendationId,
      );
      if (mounted) {
        setState(() {
          _trace = trace;
          _isLoading = false;
          if (trace == null && widget.recommendation == null) {
            _errorMessage = 'Trace details not available for this item.';
          }
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _errorMessage = 'Failed to load trace details: $e';
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      constraints: BoxConstraints(
        maxHeight: MediaQuery.of(context).size.height * 0.88,
      ),
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: Column(
        children: [
          // Header Drag Handle
          const SizedBox(height: 12),
          Center(
            child: Container(
              width: 44,
              height: 5,
              decoration: BoxDecoration(
                color: Colors.grey.shade300,
                borderRadius: BorderRadius.circular(3),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Title bar
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: AppColors.primaryBlue.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Icon(LucideIcons.gitBranch, color: AppColors.primaryBlue, size: 22),
                ),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        '7-Stage Decision Trace',
                        style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                      ),
                      Text(
                        'Explainable AI Audit Log • TWIN Engine',
                        style: TextStyle(fontSize: 12, color: Colors.grey.shade600),
                      ),
                    ],
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.close),
                  onPressed: () => Navigator.of(context).pop(),
                ),
              ],
            ),
          ),
          const Divider(height: 24),

          // Content body
          Expanded(
            child: _buildBody(),
          ),
        ],
      ),
    );
  }

  Widget _buildBody() {
    if (_isLoading) {
      return const Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CircularProgressIndicator(strokeWidth: 2.5),
            SizedBox(height: 16),
            Text('Loading transparent decision audit trace...'),
          ],
        ),
      );
    }

    if (_errorMessage != null && _trace == null && widget.recommendation == null) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(LucideIcons.alertCircle, size: 42, color: Colors.amber.shade700),
              const SizedBox(height: 12),
              Text(_errorMessage!, textAlign: TextAlign.center),
              const SizedBox(height: 16),
              ElevatedButton(
                onPressed: _fetchTrace,
                child: const Text('Retry'),
              ),
            ],
          ),
        ),
      );
    }

    return ListView(
      padding: const EdgeInsets.fromLTRB(20, 0, 20, 24),
      children: [
        _buildStageCard(
          stageNum: 1,
          title: 'OBSERVED',
          subtitle: 'Physical Sensors & Multi-Modal Telemetry',
          icon: LucideIcons.activity,
          color: Colors.blue.shade700,
          child: _buildObservedContent(),
        ),
        _buildStageCard(
          stageNum: 2,
          title: 'CONTEXT',
          subtitle: 'Clinical Trajectory & Care Constraints',
          icon: LucideIcons.fileText,
          color: Colors.teal.shade700,
          child: _buildContextContent(),
        ),
        _buildStageCard(
          stageNum: 3,
          title: 'WHY NOW',
          subtitle: 'Opportunity Engine & Timing Feasibility',
          icon: LucideIcons.clock,
          color: Colors.indigo.shade700,
          child: _buildWhyNowContent(),
        ),
        _buildStageCard(
          stageNum: 4,
          title: 'DECISION',
          subtitle: 'Deterministic Evaluation Rule & Rationale',
          icon: LucideIcons.cpu,
          color: Colors.purple.shade700,
          child: _buildDecisionContent(),
        ),
        _buildStageCard(
          stageNum: 5,
          title: 'ACTION',
          subtitle: 'Patient Prompt & FollowUpPlan Trigger',
          icon: LucideIcons.send,
          color: Colors.orange.shade800,
          child: _buildActionContent(),
        ),
        _buildStageCard(
          stageNum: 6,
          title: 'OUTCOME',
          subtitle: 'Closed-Loop Post-Intervention Validation',
          icon: LucideIcons.checkCircle2,
          color: _trace?.outcomeObserved != null ? Colors.green.shade700 : Colors.grey.shade600,
          child: _buildOutcomeContent(),
        ),
        _buildStageCard(
          stageNum: 7,
          title: 'LEARNING',
          subtitle: 'Autonomous Behavioral Memory Adaptation',
          icon: LucideIcons.sparkles,
          color: _trace?.learningDelta != null ? AppColors.primaryBlue : Colors.grey.shade600,
          child: _buildLearningContent(),
        ),
      ],
    );
  }

  Widget _buildStageCard({
    required int stageNum,
    required String title,
    required String subtitle,
    required IconData icon,
    required Color color,
    required Widget child,
  }) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      decoration: BoxDecoration(
        color: Colors.grey.shade50,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: color.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Row(
                    children: [
                      Icon(icon, size: 14, color: color),
                      const SizedBox(width: 5),
                      Text(
                        'STAGE $stageNum • $title',
                        style: TextStyle(
                          color: color,
                          fontSize: 11,
                          fontWeight: FontWeight.w700,
                          letterSpacing: 0.4,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 6),
            Text(
              subtitle,
              style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Colors.grey.shade800),
            ),
            const SizedBox(height: 12),
            child,
          ],
        ),
      ),
    );
  }

  Widget _buildObservedContent() {
    final signals = _trace?.observedSignals ?? {};
    if (signals.isEmpty && widget.recommendation != null) {
      final refs = widget.recommendation!.evidenceReferences;
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: refs.map((ref) => Padding(
          padding: const EdgeInsets.only(bottom: 4),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Icon(Icons.check, size: 14, color: Colors.blue),
              const SizedBox(width: 6),
              Expanded(child: Text(ref, style: const TextStyle(fontSize: 12))),
            ],
          ),
        )).toList(),
      );
    }

    return Wrap(
      spacing: 8,
      runSpacing: 8,
      children: signals.entries.map((e) {
        if (e.value == null) return const SizedBox.shrink();
        return Container(
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: Colors.grey.shade300),
          ),
          child: Text(
            '${e.key}: ${e.value}',
            style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w500),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildContextContent() {
    final ctx = _trace?.careContext ?? {};
    final meds = (ctx['active_medications'] as List<dynamic>?)?.map((e) => e.toString()).toList() ?? [];
    final gaps = (ctx['care_gaps'] as List<dynamic>?)?.map((e) => e.toString()).toList() ?? [];
    final trajectory = ctx['recovery_trajectory'] ?? 'STABLE';
    final risk = ctx['risk_level'] ?? 'LOW';

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            _buildBadge('Trajectory: $trajectory', Colors.teal),
            const SizedBox(width: 8),
            _buildBadge('Risk: $risk', Colors.blueGrey),
          ],
        ),
        if (meds.isNotEmpty) ...[
          const SizedBox(height: 8),
          Text('Active Medications: ${meds.join(", ")}',
              style: TextStyle(fontSize: 12, color: Colors.grey.shade700)),
        ],
        if (gaps.isNotEmpty) ...[
          const SizedBox(height: 4),
          Text('Care Gaps Monitored: ${gaps.join(", ")}',
              style: TextStyle(fontSize: 12, color: Colors.grey.shade700)),
        ],
      ],
    );
  }

  Widget _buildWhyNowContent() {
    final why = _trace?.whyNow ?? 'Evaluation criteria met; no quiet-hour or frequency cooldown conflict detected.';
    return Text(
      why,
      style: const TextStyle(fontSize: 12.5, height: 1.4),
    );
  }

  Widget _buildDecisionContent() {
    final dec = _trace?.decision ?? widget.recommendation?.reason ?? 'Proactive intervention triggered by deterministic health rule.';
    return Text(
      dec,
      style: const TextStyle(fontSize: 12.5, fontWeight: FontWeight.w500, height: 1.4),
    );
  }

  Widget _buildActionContent() {
    final act = _trace?.actionPrompt ?? widget.recommendation?.personalizedText ?? widget.recommendation?.reason ?? 'Recommendation suggested to patient.';
    final planId = widget.recommendation?.followUpPlanId;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(act, style: const TextStyle(fontSize: 12.5, height: 1.4)),
        if (planId != null) ...[
          const SizedBox(height: 6),
          _buildBadge('FollowUpPlan: $planId', Colors.orange.shade800),
        ],
      ],
    );
  }

  Widget _buildOutcomeContent() {
    final outcome = _trace?.outcomeObserved;
    if (outcome == null) {
      return Row(
        children: [
          const Icon(LucideIcons.hourglass, size: 14, color: Colors.grey),
          const SizedBox(width: 6),
          Expanded(
            child: Text(
              'Awaiting post-intervention sensor confirmation (30m verification window active).',
              style: TextStyle(fontSize: 12, fontStyle: FontStyle.italic, color: Colors.grey.shade600),
            ),
          ),
        ],
      );
    }

    return Container(
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: Colors.green.shade50,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.green.shade200),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(LucideIcons.checkCheck, size: 16, color: Colors.green.shade700),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              outcome,
              style: TextStyle(fontSize: 12, color: Colors.green.shade900, fontWeight: FontWeight.w500),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildLearningContent() {
    final delta = _trace?.learningDelta;
    if (delta == null) {
      return Row(
        children: [
          const Icon(LucideIcons.brain, size: 14, color: Colors.grey),
          const SizedBox(width: 6),
          Expanded(
            child: Text(
              'Memory will adapt autonomously once physical movement outcome is verified.',
              style: TextStyle(fontSize: 12, fontStyle: FontStyle.italic, color: Colors.grey.shade600),
            ),
          ),
        ],
      );
    }

    return Container(
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: AppColors.primaryBlue.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: AppColors.primaryBlue.withValues(alpha: 0.2)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(LucideIcons.zap, size: 16, color: AppColors.primaryBlue),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              delta,
              style: TextStyle(fontSize: 12, color: AppColors.primaryBlue, fontWeight: FontWeight.w600),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBadge(String label, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(6),
        border: Border.all(color: color.withValues(alpha: 0.3)),
      ),
      child: Text(
        label,
        style: TextStyle(fontSize: 11, fontWeight: FontWeight.w600, color: color),
      ),
    );
  }
}
